image: gitpod/workspace-node

tasks:
  - init: npm install
    command: npm test

vscode:
  extensions:
    - "ms-playwright.playwright"
    - "dbaeumer.vscode-eslint"
    - "esbenp.prettier-vscode"
    - "github.vscode-pull-request-github"
    - "eamodio.gitlens"
